### PR TITLE
Remove deprecated file open mode 'rU'

### PR DESCRIPTION
**Pull request by neoformit**
Hoping this will fix the following error. `planemo test` passes with this:

```
Traceback (most recent call last):
  File "/mnt/tools/shed_tools/toolshed.g2.bx.psu.edu/repos/peterjc/seq_filter_by_id/83a19df00eab/seq_filter_by_id/tools/seq_filter_by_id/seq_filter_by_id.py", line 250, in <module>
    handle = open(tabular_file, "rU")
             ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
```

### CODE REVIEW

**Comment by peterjc** [comment]
Thanks. It looks like Python 3.11 turned the warning into an error https://bugs.python.org/issue37330 (not tested to confirm, certainly Python 3.10.12 is still fine).

**Comment by peterjc** [comment]
I'm working on this now - it applies to multiple tools in the repository, and then they need version bumps.

**Comment by peterjc** [comment]
This will most likely break things under Python 2 (should anyone be mixing their line endings), but that's acceptable at this point in time.

**Comment by peterjc** [comment]
seq_filter_by_id v0.2.9 is not on the main Tool Shed with your fix - thank you!

(I have not yet updated the rest, I aim to fix #40 first to have automated testing and deployment working again)

**Comment by neoformit** [comment]
Brilliant thanks for the quick response Peter

**Pull request merged**
