### PR TITLE
Migrate seq_filter_by_id to conda

### PR DESCRIPTION
**Pull request by abretaud**
Hi,
Here's a little change to seq_filter_by_id to make it work properly with conda.
The biopython requirement was not sufficient as the py script fails with python 3.x

### CODE REVIEW

**Comment by peterjc** [comment]
I currently intend all my scripts to work on both Python 2 and 3 seamlessly. How did it break?

For now I am deliberately supporting the legacy ``tool_dependencies.xml`` system (we still use it locally).

**Comment by abretaud** [comment]
Ok, it makes sense!
Here's the error:

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/....../shed_tools/toolshed.g2.bx.psu.edu/repos/peterjc/seq_select_by_id/8e1a90917fa7/seq_select_by_id/tools/seq_select_by_id/seq_select_by_id.py", line 135, in 
    out_handle.write(records.get_raw(name))
TypeError: write() argument must be str, not bytes
```

**Comment by peterjc** [comment]
Ah - I know how to fix that one, hang on...

**Comment by peterjc** [comment]
The code on GitHub should work under Python 3 already, seq_select_by_id v0.0.14
https://github.com/peterjc/pico_galaxy/commit/197146234abffb0ad042da56cbc37a7dcfd21dcd

Sadly it looks like I didn't push that to the main Tool Shed, done now. Sorry about that. Could you update and re-test please?

**Comment by peterjc** [comment]
What's the error you saw with seq_filter_by_id? Testing locally outside of Galaxy this seems happy under Python 3.

**Comment by abretaud** [comment]
Ok, looks good, thanks! You can close this
For seq_filter_by_id, I just thought that there was probably the same problem

**Comment by peterjc** [comment]
Excellent, closing issue.

Thanks for reporting this which triggered getting seq_select_by_id v0.0.14 released 👍

**Pull request closed without merging**
