### PR TITLE
Fixing python2.7 and python3 compatibility issue

### PR DESCRIPTION
**Pull request by Neato-Nick**
Original traceback:
```
Traceback (most recent call last):
  File "/home/nicholas.carleson@usda-ars.orst.edu/opt/pico_galaxy/tools/protein_analysis/seq_analysis_utils.py", line 111, in fasta_iterator
    raise StopIteration
StopIteration
```

### CODE REVIEW

**Comment by peterjc** [comment]
Thanks for the stacktrace, I think the fix is even simpler - remove the ``raise StopIteration`` line. Can you try that quickly?

**Comment by Neato-Nick** [comment]
Hah, that also works! Very simple fix after all

**Comment by peterjc** [comment]
OK, this needs a version bump and pushing to the toolshed now... hang on.

**Comment by peterjc** [comment]
That's on the tool shed now as v0.2.13 - Python 3 fix for raising StopIteration

**Pull request merged**
