### PR TITLE
GFF3 output for get_orfs_or_cdss

### PR DESCRIPTION
**Pull request by erasche**
Now that we've moved to WebApollo, our users have to have "evidence" for gene calls, which means I'm forced to add a six-pack track for cases where the gene callers get it flat wrong, thus I need gff3 output. So, here ya go.

### CODE REVIEW

**Comment by peterjc** [comment]
Thanks - merged with a version bump https://github.com/peterjc/pico_galaxy/commit/c143b7e6dab19a10cc95345c48e80f2891aeee41 and further tweak https://github.com/peterjc/pico_galaxy/commit/bcbd605744dec2b3cac90729fffb5905bf15f2da

It looks like the TravisCI setup needs some tweaking... probably the base VM image has changed.

**Comment by erasche** [comment]
Ach, version bump, knew I forgot something. Thanks @peterjc

**Comment by peterjc** [comment]
That's on the main and test Tool Shed now.

**Comment by erasche** [comment]
Cheers mate.

lør. 9. jan. 2016 kl. 22.43 skrev Peter Cock <notifications@github.com>:

**Pull request merged**
