### PR TITLE
seq_filter_by_id skip empty lines

### PR DESCRIPTION
**Pull request by lecorguille**
Hi Peter,
One of our users had an empty line at the end of her ID list.
I just add a continue to skip those empty lines.
Cheers

### CODE REVIEW

**Comment by peterjc** [comment]
The TravisCI tests are failing as I've not turned off Python 2.6 (yet), and another unrelated dependency is failing to download :(

**Comment by peterjc** [comment]
Anyway, the change looks sensible - I'm happy to bump the version number, and thank you in the change log.

**Comment by peterjc** [comment]
That's now on the TTS and main TS as v0.2.3, thank you!

**Comment by lecorguille** [comment]
Thank to you!

**Pull request merged**
